// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: transcriber.proto

package transcriberv1

import (
	duration "github.com/golang/protobuf/ptypes/duration"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Indicates the type of speech event.
type SpeechEventType int32

const (
	// No speech event specified.
	SpeechEventType_SPEECH_EVENT_TYPE_UNSPECIFIED SpeechEventType = 0
	// This event indicates that the server has detected the end of the user's
	// speech utterance and expects no additional speech. Therefore, the server
	// will not process additional audio and will close the gRPC bidirectional
	// stream. This event is only sent if there was a force cutoff due to
	// silence being detected early.
	SpeechEventType_END_OF_SINGLE_UTTERANCE SpeechEventType = 1
	// This event indicates that the server has detected the beginning of human
	// voice activity in the stream. This event can be returned multiple times
	// if speech starts and stops repeatedly throughout the stream. This event
	// is only sent if `voice_activity_events` is set to true.
	SpeechEventType_SPEECH_ACTIVITY_BEGIN SpeechEventType = 2
	// This event indicates that the server has detected the end of human voice
	// activity in the stream. This event can be returned multiple times if
	// speech starts and stops repeatedly throughout the stream. This event is
	// only sent if `voice_activity_events` is set to true.
	SpeechEventType_SPEECH_ACTIVITY_END SpeechEventType = 3
)

// Enum value maps for SpeechEventType.
var (
	SpeechEventType_name = map[int32]string{
		0: "SPEECH_EVENT_TYPE_UNSPECIFIED",
		1: "END_OF_SINGLE_UTTERANCE",
		2: "SPEECH_ACTIVITY_BEGIN",
		3: "SPEECH_ACTIVITY_END",
	}
	SpeechEventType_value = map[string]int32{
		"SPEECH_EVENT_TYPE_UNSPECIFIED": 0,
		"END_OF_SINGLE_UTTERANCE":       1,
		"SPEECH_ACTIVITY_BEGIN":         2,
		"SPEECH_ACTIVITY_END":           3,
	}
)

func (x SpeechEventType) Enum() *SpeechEventType {
	p := new(SpeechEventType)
	*p = x
	return p
}

func (x SpeechEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpeechEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_transcriber_proto_enumTypes[0].Descriptor()
}

func (SpeechEventType) Type() protoreflect.EnumType {
	return &file_transcriber_proto_enumTypes[0]
}

func (x SpeechEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpeechEventType.Descriptor instead.
func (SpeechEventType) EnumDescriptor() ([]byte, []int) {
	return file_transcriber_proto_rawDescGZIP(), []int{0}
}

// Indicates the expected quality of transcription.
// follows this law :-> you can control any two quality, speed and price
type TranscribeConfig_Quality int32

const (
	// Here we value the speed of transcription, anything goes
	TranscribeConfig_LOW TranscribeConfig_Quality = 0
	// This is the default with a good balance on speed and accuracy of the transcription
	TranscribeConfig_MEDIUM TranscribeConfig_Quality = 1
	// The best available quality is what we care about, throw all the available resources to fullfil this goal.
	TranscribeConfig_HIGH TranscribeConfig_Quality = 2
)

// Enum value maps for TranscribeConfig_Quality.
var (
	TranscribeConfig_Quality_name = map[int32]string{
		0: "LOW",
		1: "MEDIUM",
		2: "HIGH",
	}
	TranscribeConfig_Quality_value = map[string]int32{
		"LOW":    0,
		"MEDIUM": 1,
		"HIGH":   2,
	}
)

func (x TranscribeConfig_Quality) Enum() *TranscribeConfig_Quality {
	p := new(TranscribeConfig_Quality)
	*p = x
	return p
}

func (x TranscribeConfig_Quality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranscribeConfig_Quality) Descriptor() protoreflect.EnumDescriptor {
	return file_transcriber_proto_enumTypes[1].Descriptor()
}

func (TranscribeConfig_Quality) Type() protoreflect.EnumType {
	return &file_transcriber_proto_enumTypes[1]
}

func (x TranscribeConfig_Quality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranscribeConfig_Quality.Descriptor instead.
func (TranscribeConfig_Quality) EnumDescriptor() ([]byte, []int) {
	return file_transcriber_proto_rawDescGZIP(), []int{0, 0}
}

// The encoding of the audio data sent in the request.
//
// All encodings support only 1 channel (mono) audio, unless the
// `audio_channel_count` and `enable_separate_recognition_per_channel` fields
// are set.
//
// For best results, the audio source should be captured and transmitted using
// a lossless encoding (`FLAC` or `LINEAR16`). The accuracy of the speech
// recognition can be reduced if lossy codecs are used to capture or transmit
// audio, particularly if background noise is present. Lossy codecs include
// `MULAW`, `AMR`, `AMR_WB`, `OGG_OPUS`, `SPEEX_WITH_HEADER_BYTE`, `MP3`,
// and `WEBM_OPUS`.
//
// The `FLAC` and `WAV` audio file formats include a header that describes the
// included audio content. You can request recognition for `WAV` files that
// contain either `LINEAR16` or `MULAW` encoded audio.
// If you send `FLAC` or `WAV` audio file format in
// your request, you do not need to specify an `AudioEncoding`; the audio
// encoding format is determined from the file header. If you specify
// an `AudioEncoding` when you send  send `FLAC` or `WAV` audio, the
// encoding configuration must match the encoding described in the audio
// header; otherwise the request returns an
// [google.rpc.Code.INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT] error
// code.
type TranscribeConfig_AudioEncoding int32

const (
	// Not specified.
	TranscribeConfig_ENCODING_UNSPECIFIED TranscribeConfig_AudioEncoding = 0
	// Uncompressed 16-bit signed little-endian samples (Linear PCM).
	TranscribeConfig_LINEAR16 TranscribeConfig_AudioEncoding = 1
	// `FLAC` (Free Lossless Audio
	// Codec) is the recommended encoding because it is
	// lossless--therefore recognition is not compromised--and
	// requires only about half the bandwidth of `LINEAR16`. `FLAC` stream
	// encoding supports 16-bit and 24-bit samples, however, not all fields in
	// `STREAMINFO` are supported.
	TranscribeConfig_FLAC TranscribeConfig_AudioEncoding = 2
	// 8-bit samples that compand 14-bit audio samples using G.711 PCMU/mu-law.
	TranscribeConfig_MULAW TranscribeConfig_AudioEncoding = 3
	// Adaptive Multi-Rate Narrowband codec. `sample_rate_hertz` must be 8000.
	TranscribeConfig_AMR TranscribeConfig_AudioEncoding = 4
	// Adaptive Multi-Rate Wideband codec. `sample_rate_hertz` must be 16000.
	TranscribeConfig_AMR_WB TranscribeConfig_AudioEncoding = 5
	// Opus encoded audio frames in Ogg container
	// ([OggOpus](https://wiki.xiph.org/OggOpus)).
	// `sample_rate_hertz` must be one of 8000, 12000, 16000, 24000, or 48000.
	TranscribeConfig_OGG_OPUS TranscribeConfig_AudioEncoding = 6
	// Although the use of lossy encodings is not recommended, if a very low
	// bitrate encoding is required, `OGG_OPUS` is highly preferred over
	// Speex encoding. The [Speex](https://speex.org/)  encoding supported by
	// Cloud Speech API has a header byte in each block, as in MIME type
	// `audio/x-speex-with-header-byte`.
	// It is a variant of the RTP Speex encoding defined in
	// [RFC 5574](https://tools.ietf.org/html/rfc5574).
	// The stream is a sequence of blocks, one block per RTP packet. Each block
	// starts with a byte containing the length of the block, in bytes, followed
	// by one or more frames of Speex data, padded to an integral number of
	// bytes (octets) as specified in RFC 5574. In other words, each RTP header
	// is replaced with a single byte containing the block length. Only Speex
	// wideband is supported. `sample_rate_hertz` must be 16000.
	TranscribeConfig_SPEEX_WITH_HEADER_BYTE TranscribeConfig_AudioEncoding = 7
	// Opus encoded audio frames in WebM container
	// ([OggOpus](https://wiki.xiph.org/OggOpus)). `sample_rate_hertz` must be
	// one of 8000, 12000, 16000, 24000, or 48000.
	TranscribeConfig_WEBM_OPUS TranscribeConfig_AudioEncoding = 9
)

// Enum value maps for TranscribeConfig_AudioEncoding.
var (
	TranscribeConfig_AudioEncoding_name = map[int32]string{
		0: "ENCODING_UNSPECIFIED",
		1: "LINEAR16",
		2: "FLAC",
		3: "MULAW",
		4: "AMR",
		5: "AMR_WB",
		6: "OGG_OPUS",
		7: "SPEEX_WITH_HEADER_BYTE",
		9: "WEBM_OPUS",
	}
	TranscribeConfig_AudioEncoding_value = map[string]int32{
		"ENCODING_UNSPECIFIED":   0,
		"LINEAR16":               1,
		"FLAC":                   2,
		"MULAW":                  3,
		"AMR":                    4,
		"AMR_WB":                 5,
		"OGG_OPUS":               6,
		"SPEEX_WITH_HEADER_BYTE": 7,
		"WEBM_OPUS":              9,
	}
)

func (x TranscribeConfig_AudioEncoding) Enum() *TranscribeConfig_AudioEncoding {
	p := new(TranscribeConfig_AudioEncoding)
	*p = x
	return p
}

func (x TranscribeConfig_AudioEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranscribeConfig_AudioEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_transcriber_proto_enumTypes[2].Descriptor()
}

func (TranscribeConfig_AudioEncoding) Type() protoreflect.EnumType {
	return &file_transcriber_proto_enumTypes[2]
}

func (x TranscribeConfig_AudioEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranscribeConfig_AudioEncoding.Descriptor instead.
func (TranscribeConfig_AudioEncoding) EnumDescriptor() ([]byte, []int) {
	return file_transcriber_proto_rawDescGZIP(), []int{0, 1}
}

// Configuration at the start of streaming request
type TranscribeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Defines the quality with which our transcription is performed
	QualityType TranscribeConfig_Quality `protobuf:"varint,1,opt,name=quality_type,json=qualityType,proto3,enum=apis.TranscribeConfig_Quality" json:"quality_type,omitempty"`
	// Encoding of audio data sent in all `RecognitionAudio` messages.
	// This field is optional for `FLAC` and `WAV` audio files and required
	// for all other audio formats.
	Encoding TranscribeConfig_AudioEncoding `protobuf:"varint,2,opt,name=encoding,proto3,enum=apis.TranscribeConfig_AudioEncoding" json:"encoding,omitempty"`
	// Defines the audio configuration that may be useful on the server side process
	DecodingSamplingRate int32 `protobuf:"varint,3,opt,name=decoding_sampling_rate,json=decodingSamplingRate,proto3" json:"decoding_sampling_rate,omitempty"`
	// Defines the audio channel count
	DecodingAudioChannelCount int32 `protobuf:"varint,4,opt,name=decoding_audio_channel_count,json=decodingAudioChannelCount,proto3" json:"decoding_audio_channel_count,omitempty"`
}

func (x *TranscribeConfig) Reset() {
	*x = TranscribeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcriber_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscribeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeConfig) ProtoMessage() {}

func (x *TranscribeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_transcriber_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeConfig.ProtoReflect.Descriptor instead.
func (*TranscribeConfig) Descriptor() ([]byte, []int) {
	return file_transcriber_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeConfig) GetQualityType() TranscribeConfig_Quality {
	if x != nil {
		return x.QualityType
	}
	return TranscribeConfig_LOW
}

func (x *TranscribeConfig) GetEncoding() TranscribeConfig_AudioEncoding {
	if x != nil {
		return x.Encoding
	}
	return TranscribeConfig_ENCODING_UNSPECIFIED
}

func (x *TranscribeConfig) GetDecodingSamplingRate() int32 {
	if x != nil {
		return x.DecodingSamplingRate
	}
	return 0
}

func (x *TranscribeConfig) GetDecodingAudioChannelCount() int32 {
	if x != nil {
		return x.DecodingAudioChannelCount
	}
	return 0
}

// Word-specific information for recognized words.
type VoiceText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The word corresponding to this set of information.
	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The confidence estimate between 0.0 and 1.0. A higher number
	// indicates an estimated greater likelihood that the recognized words are
	// correct.
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// A distinct label is assigned for every speaker within the audio. This field
	// specifies which one of those speakers was detected to have spoken this
	// word.
	SpeakerLabel string `protobuf:"bytes,3,opt,name=speaker_label,json=speakerLabel,proto3" json:"speaker_label,omitempty"`
	// A label to show which language the text/data shared is in. The value can be
	// blank if the system is not able to determine the language of the text.
	Language string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *VoiceText) Reset() {
	*x = VoiceText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcriber_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoiceText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceText) ProtoMessage() {}

func (x *VoiceText) ProtoReflect() protoreflect.Message {
	mi := &file_transcriber_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceText.ProtoReflect.Descriptor instead.
func (*VoiceText) Descriptor() ([]byte, []int) {
	return file_transcriber_proto_rawDescGZIP(), []int{1}
}

func (x *VoiceText) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *VoiceText) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *VoiceText) GetSpeakerLabel() string {
	if x != nil {
		return x.SpeakerLabel
	}
	return ""
}

func (x *VoiceText) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// `TranscribeResponse` is the only message returned to the client.
// A series of zero or more `TranscribeResponse`
// messages are streamed back to the client. If there is no recognizable
// audio then no messages are streamed back to the client.
//
//   - In each response, only one of these fields will be set:
//     `error`,
//     `speech_event_type`, or
//     one or more (repeated) `results`.
type TranscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This repeated list contains zero or more results that
	// correspond to consecutive portions of the audio currently being processed.
	// It contains zero or one results (the interim results).
	Results []*VoiceText `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	// Indicates the type of speech event.
	SpeechEventType SpeechEventType `protobuf:"varint,3,opt,name=speech_event_type,json=speechEventType,proto3,enum=apis.SpeechEventType" json:"speech_event_type,omitempty"`
	// Time offset between the beginning of the audio and event emission.
	SpeechEventOffset *duration.Duration `protobuf:"bytes,7,opt,name=speech_event_offset,json=speechEventOffset,proto3" json:"speech_event_offset,omitempty"`
	Provisional       bool               `protobuf:"varint,8,opt,name=provisional,proto3" json:"provisional,omitempty"`
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcriber_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transcriber_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_transcriber_proto_rawDescGZIP(), []int{2}
}

func (x *TranscribeResponse) GetResults() []*VoiceText {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *TranscribeResponse) GetSpeechEventType() SpeechEventType {
	if x != nil {
		return x.SpeechEventType
	}
	return SpeechEventType_SPEECH_EVENT_TYPE_UNSPECIFIED
}

func (x *TranscribeResponse) GetSpeechEventOffset() *duration.Duration {
	if x != nil {
		return x.SpeechEventOffset
	}
	return nil
}

func (x *TranscribeResponse) GetProvisional() bool {
	if x != nil {
		return x.Provisional
	}
	return false
}

// Request message for the
// [TranscribeRequest]
// [audio][google.cloud.speech.v2.StreamingRecognizeRequest.audio]. All
// subsequent messages must contain
// [audio][google.cloud.speech.v2.StreamingRecognizeRequest.audio] and must not
// contain a
// [streaming_config][google.cloud.speech.v2.StreamingRecognizeRequest.streaming_config]
// message.
type TranscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*TranscribeRequest_Configuration
	//	*TranscribeRequest_SpeechEventType
	//	*TranscribeRequest_Audio
	Request isTranscribeRequest_Request `protobuf_oneof:"request"`
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transcriber_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcriber_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_transcriber_proto_rawDescGZIP(), []int{3}
}

func (m *TranscribeRequest) GetRequest() isTranscribeRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *TranscribeRequest) GetConfiguration() *TranscribeConfig {
	if x, ok := x.GetRequest().(*TranscribeRequest_Configuration); ok {
		return x.Configuration
	}
	return nil
}

func (x *TranscribeRequest) GetSpeechEventType() SpeechEventType {
	if x, ok := x.GetRequest().(*TranscribeRequest_SpeechEventType); ok {
		return x.SpeechEventType
	}
	return SpeechEventType_SPEECH_EVENT_TYPE_UNSPECIFIED
}

func (x *TranscribeRequest) GetAudio() []byte {
	if x, ok := x.GetRequest().(*TranscribeRequest_Audio); ok {
		return x.Audio
	}
	return nil
}

type isTranscribeRequest_Request interface {
	isTranscribeRequest_Request()
}

type TranscribeRequest_Configuration struct {
	// Options to customize transcription service
	Configuration *TranscribeConfig `protobuf:"bytes,1,opt,name=configuration,proto3,oneof"`
}

type TranscribeRequest_SpeechEventType struct {
	// Indicates the type of speech event.
	SpeechEventType SpeechEventType `protobuf:"varint,3,opt,name=speech_event_type,json=speechEventType,proto3,enum=apis.SpeechEventType,oneof"`
}

type TranscribeRequest_Audio struct {
	// Inline audio bytes to be Recognized.
	// Maximum size for this field is 15 KB per request.
	Audio []byte `protobuf:"bytes,5,opt,name=audio,proto3,oneof"`
}

func (*TranscribeRequest_Configuration) isTranscribeRequest_Request() {}

func (*TranscribeRequest_SpeechEventType) isTranscribeRequest_Request() {}

func (*TranscribeRequest_Audio) isTranscribeRequest_Request() {}

var File_transcriber_proto protoreflect.FileDescriptor

var file_transcriber_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x70, 0x69, 0x73, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x03, 0x0a, 0x10, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x41,
	0x0a, 0x0c, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x51, 0x75, 0x61,
	0x6c, 0x69, 0x74, 0x79, 0x52, 0x0b, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x40, 0x0a, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64,
	0x69, 0x6e, 0x67, 0x12, 0x34, 0x0a, 0x16, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x5f,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x14, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x61, 0x6d,
	0x70, 0x6c, 0x69, 0x6e, 0x67, 0x52, 0x61, 0x74, 0x65, 0x12, 0x3f, 0x0a, 0x1c, 0x64, 0x65, 0x63,
	0x6f, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x19, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x07, 0x51, 0x75,
	0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x49,
	0x47, 0x48, 0x10, 0x02, 0x22, 0x9a, 0x01, 0x0a, 0x0d, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x4e, 0x43, 0x4f, 0x44, 0x49,
	0x4e, 0x47, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x49, 0x4e, 0x45, 0x41, 0x52, 0x31, 0x36, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x46, 0x4c, 0x41, 0x43, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x55, 0x4c, 0x41,
	0x57, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4d, 0x52, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06,
	0x41, 0x4d, 0x52, 0x5f, 0x57, 0x42, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x47, 0x47, 0x5f,
	0x4f, 0x50, 0x55, 0x53, 0x10, 0x06, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x50, 0x45, 0x45, 0x58, 0x5f,
	0x57, 0x49, 0x54, 0x48, 0x5f, 0x48, 0x45, 0x41, 0x44, 0x45, 0x52, 0x5f, 0x42, 0x59, 0x54, 0x45,
	0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x45, 0x42, 0x4d, 0x5f, 0x4f, 0x50, 0x55, 0x53, 0x10,
	0x09, 0x22, 0x80, 0x01, 0x0a, 0x09, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x5f, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x70, 0x65, 0x61,
	0x6b, 0x65, 0x72, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x22, 0xef, 0x01, 0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61,
	0x70, 0x69, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x54, 0x65, 0x78, 0x74, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x41, 0x0a, 0x11, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68,
	0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x49, 0x0a, 0x13, 0x73, 0x70, 0x65,
	0x65, 0x63, 0x68, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x11, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x22, 0xbb, 0x01, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x11,
	0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x53,
	0x70, 0x65, 0x65, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00,
	0x52, 0x0f, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2a, 0x85, 0x01, 0x0a, 0x0f, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x1d, 0x53, 0x50, 0x45, 0x45,
	0x43, 0x48, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17, 0x45,
	0x4e, 0x44, 0x5f, 0x4f, 0x46, 0x5f, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x5f, 0x55, 0x54, 0x54,
	0x45, 0x52, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x50, 0x45, 0x45,
	0x43, 0x48, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x49, 0x54, 0x59, 0x5f, 0x42, 0x45, 0x47, 0x49,
	0x4e, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x50, 0x45, 0x45, 0x43, 0x48, 0x5f, 0x41, 0x43,
	0x54, 0x49, 0x56, 0x49, 0x54, 0x59, 0x5f, 0x45, 0x4e, 0x44, 0x10, 0x03, 0x32, 0x5b, 0x0a, 0x12,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x73,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x33, 0x0a, 0x1e, 0x63, 0x6f, 0x6d,
	0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x74, 0x79, 0x70, 0x65, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x0f, 0x2e,
	0x3b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transcriber_proto_rawDescOnce sync.Once
	file_transcriber_proto_rawDescData = file_transcriber_proto_rawDesc
)

func file_transcriber_proto_rawDescGZIP() []byte {
	file_transcriber_proto_rawDescOnce.Do(func() {
		file_transcriber_proto_rawDescData = protoimpl.X.CompressGZIP(file_transcriber_proto_rawDescData)
	})
	return file_transcriber_proto_rawDescData
}

var file_transcriber_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_transcriber_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transcriber_proto_goTypes = []interface{}{
	(SpeechEventType)(0),                // 0: apis.SpeechEventType
	(TranscribeConfig_Quality)(0),       // 1: apis.TranscribeConfig.Quality
	(TranscribeConfig_AudioEncoding)(0), // 2: apis.TranscribeConfig.AudioEncoding
	(*TranscribeConfig)(nil),            // 3: apis.TranscribeConfig
	(*VoiceText)(nil),                   // 4: apis.VoiceText
	(*TranscribeResponse)(nil),          // 5: apis.TranscribeResponse
	(*TranscribeRequest)(nil),           // 6: apis.TranscribeRequest
	(*duration.Duration)(nil),           // 7: google.protobuf.Duration
}
var file_transcriber_proto_depIdxs = []int32{
	1, // 0: apis.TranscribeConfig.quality_type:type_name -> apis.TranscribeConfig.Quality
	2, // 1: apis.TranscribeConfig.encoding:type_name -> apis.TranscribeConfig.AudioEncoding
	4, // 2: apis.TranscribeResponse.results:type_name -> apis.VoiceText
	0, // 3: apis.TranscribeResponse.speech_event_type:type_name -> apis.SpeechEventType
	7, // 4: apis.TranscribeResponse.speech_event_offset:type_name -> google.protobuf.Duration
	3, // 5: apis.TranscribeRequest.configuration:type_name -> apis.TranscribeConfig
	0, // 6: apis.TranscribeRequest.speech_event_type:type_name -> apis.SpeechEventType
	6, // 7: apis.TranscriberService.Transcribe:input_type -> apis.TranscribeRequest
	5, // 8: apis.TranscriberService.Transcribe:output_type -> apis.TranscribeResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_transcriber_proto_init() }
func file_transcriber_proto_init() {
	if File_transcriber_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transcriber_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscribeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transcriber_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoiceText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transcriber_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transcriber_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_transcriber_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*TranscribeRequest_Configuration)(nil),
		(*TranscribeRequest_SpeechEventType)(nil),
		(*TranscribeRequest_Audio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transcriber_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcriber_proto_goTypes,
		DependencyIndexes: file_transcriber_proto_depIdxs,
		EnumInfos:         file_transcriber_proto_enumTypes,
		MessageInfos:      file_transcriber_proto_msgTypes,
	}.Build()
	File_transcriber_proto = out.File
	file_transcriber_proto_rawDesc = nil
	file_transcriber_proto_goTypes = nil
	file_transcriber_proto_depIdxs = nil
}
